import streamlit as st
import pandas as pd
import numpy as np
import io
import validator
import kpi_engine

# Page Config
st.set_page_config(page_title="Supply Chain Risk Cockpit", layout="wide", page_icon="✈️")

# ---------------------------------------------------------
# Styles
# ---------------------------------------------------------
st.markdown("""
<style>
    .metric-card {
        background-color: #f0f2f6;
        padding: 15px;
        border-radius: 10px;
        text-align: center;
    }
    .action-high { color: #d32f2f; font-weight: bold; }
    .action-med { color: #f57c00; font-weight: bold; }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------
@st.cache_data
def load_excel(file_bytes):
    xls = pd.ExcelFile(io.BytesIO(file_bytes))
    dfs = {}
    for sh in xls.sheet_names:
        dfs[sh] = pd.read_excel(xls, sheet_name=sh)
    return dfs

def enrich_master(df, dfs):
    """Joins master data (unit_revenue, cogs, etc.)"""
    if "Master_Data" not in dfs:
        # Defaults
        df["unit_revenue"] = 1.0
        df["unit_cogs"] = 0.5
        return df
    
    m = dfs["Master_Data"].copy()
    # Deduplicate master
    if "location" in m.columns:
        m = m.drop_duplicates(subset=["sku", "location"])
        df = df.merge(m[["sku", "location", "unit_revenue", "unit_cogs"]], on=["sku", "location"], how="left")
    else:
        m = m.drop_duplicates(subset=["sku"])
        df = df.merge(m[["sku", "unit_revenue", "unit_cogs"]], on=["sku"], how="left")
        
    df["unit_revenue"] = df["unit_revenue"].fillna(1.0)
    df["unit_cogs"] = df["unit_cogs"].fillna(0.5)
    return df

# ---------------------------------------------------------
# Main App
# ---------------------------------------------------------
def main():
    st.title("✈️ Supply Chain Risk Cockpit (MVP)")

    # Sidebar
    st.sidebar.header("Scenario Controls")
    demand_uplift = st.sidebar.slider("Demand Uplift (%)", 0, 50, 0, 5) / 100.0
    supply_delay = st.sidebar.slider("Supply Delay (Weeks)", 0, 8, 0, 1)
    horizon = st.sidebar.slider("Planning Horizon (Weeks)", 4, 16, 8, 1)

    st.sidebar.divider()
    st.sidebar.info("Upload 'control_tower_input.xlsx' to begin.")

    # File Uploader
    uploaded_file = st.file_uploader("Upload Data", type=["xlsx"])
    
    if not uploaded_file:
        st.info("👆 Please upload the data file.")
        
        # Generator Button for user convenience (if they don't have the file)
        # Note: We can't easily auto-download the file generated by the python script client-side without serving it
        # But we can mention it exists in the repo.
        return

    # Data Processing
    try:
        file_bytes = uploaded_file.read()
        dfs = load_excel(file_bytes)
        
        # Validation
        ok, errors = validator.validate_data(dfs)
        if not ok:
            st.error("❌ Data Validation Failed")
            for e in errors:
                st.write(f"- {e}")
            st.stop()
            
        inv = dfs["Inventory"]
        demand = dfs["Demand_Plan"]
        supply = dfs["Supply_Plan"]
        
        # KPI Computation
        with st.spinner("Computing Scenarios..."):
            summary, detail = kpi_engine.compute_kpis(
                inv, demand, supply, 
                horizon_weeks=horizon,
                demand_uplift_pct=demand_uplift,
                supply_delay_weeks=supply_delay
            )
            
        # Enrichment (Economics)
        summary = enrich_master(summary, dfs)
        summary["revenue_at_risk"] = summary["total_unmet"] * summary["unit_revenue"]
        summary["stockout_impact"] = np.where(summary["first_stockout_week"].isna(), "None", summary["first_stockout_week"].astype(str))

        # -------------------
        # Executive Metrics
        # -------------------
        tot_rar = summary["revenue_at_risk"].sum()
        skus_stockout = summary["stockout_flag"].sum()
        avg_fill = summary["fill_rate"].mean()
        safety_breaches = summary["safety_breach_flag"].sum()
        
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("💰 Revenue at Risk", f"${tot_rar:,.0f}")
        col2.metric("⚠️ SKUs with Stockouts", int(skus_stockout))
        col3.metric("📉 Avg Fill Rate", f"{avg_fill*100:.1f}%")
        col4.metric("🛡️ Safety Breaches", int(safety_breaches))
        
        st.divider()
        
        # -------------------
        # Prioritized Actions
        # -------------------
        st.subheader("🔥 Top Actions (Prioritized)")
        
        # Heuristic Logic for Recommendations
        def recommend(row):
            if row["stockout_flag"]: 
                return "🟥 EXPEDITE / ALLOCATE"
            if row["safety_breach_flag"]: 
                return "🟧 REPLENISH / MONITOR"
            if row["min_poh"] > row["safety_stock_qty"] * 3 and row["min_poh"] > 10000: # Simple excess logic
                return "🟦 PROMO / REDISTRIBUTE"
            return "✅ OK"
            
        actions = summary.copy()
        actions["Recommendation"] = actions.apply(recommend, axis=1)
        actions = actions.sort_values(["revenue_at_risk", "first_stockout_week"], ascending=[False, True])
        
        # Display Table
        st.dataframe(
            actions[[
                "sku", "location", "Recommendation", 
                "revenue_at_risk", "fill_rate", 
                "first_stockout_week", "first_safety_breach_week"
            ]].style.format({
                "revenue_at_risk": "${:,.0f}",
                "fill_rate": "{:.1%}"
            }).applymap(lambda x: "color: red; font-weight: bold" if "EXPEDITE" in str(x) else ("color: orange; font-weight: bold" if "REPLENISH" in str(x) else ""), subset=["Recommendation"]),
            use_container_width=True,
            column_config={
                "first_stockout_week": st.column_config.DateColumn("1st Stockout"),
                "first_safety_breach_week": st.column_config.DateColumn("Safety Breach"),
            }
        )
        
        st.divider()

        # -------------------
        # Drilldown
        # -------------------
        st.subheader("🔍 SKU-Location Drilldown")
        
        sku_list = summary["sku"].unique()
        selected_sku = st.selectbox("Select SKU", sku_list)
        
        loc_list = summary[summary["sku"] == selected_sku]["location"].unique()
        selected_loc = st.selectbox("Select Location", loc_list)
        
        # Filter Detail
        mask = (detail["sku"] == selected_sku) & (detail["location"] == selected_loc)
        drill_df = detail[mask].copy()
        
        # Chart
        st.line_chart(drill_df.set_index("week_start")[["on_hand_qty", "forecast_qty", "supply_qty"]])
        
        # Table
        st.dataframe(
            drill_df[[
                "week_start", "forecast_qty", "supply_qty", 
                "NAI", "POH", "served_qty", "unmet_qty"
            ]].style.format("{:,.0f}"), 
            use_container_width=True
        )
        
    except Exception as e:
        st.error(f"Application Error: {str(e)}")
        # st.exception(e) # Uncomment for debug

if __name__ == "__main__":
    main()
